#! /bin/sh

#  Create the data.js file of common entity names
#  plus the entities directory of less-common ones
#  and installs them
#  
#  Usage:  ./makeAll $(MATHJAXBASEDIR)

rm -rf entities
if test -d "$1/unpacked/jax/input/MathML/entities/" ; then
	rm "$1/unpacked/jax/input/MathML/entities/"*.js
else
	echo "$0  $1: You MUST specify the MATHJAX base directory as an argument to this script!"
fi
./makeEntities
if test -d "$1/unpacked" ; then
	cp entities/*.js "$1/unpacked/jax/input/MathML/entities"
fi

#
#  This file contains the entity table to be added
#  to jax/input/MathML/jax.js
#
if test -x open; then
	open -a AlphaX data.js
fi
