#! /bin/sh

#
#  Creates the optable.js data (for inclusion on jax/element/mml/jax.js)
#  and the optable directory of auxiliary operator data.
#  Then it installs them.
#
#  Usage: ./makeAll $(MATHJAXBASEDIR)

rm optable/*.js
rm optable.js

./makeOpTable

if test -d "$1/unpacked/jax/element/mml/optable" ; then
	cp optable/*.js "$1/unpacked/jax/element/mml/optable"
else
	echo "$0  $1: You MUST specify the MATHJAX base directory as an argument to this script!"
fi

#
#  This file contains the operator table data needed
#  for the common operators, that needs to be included
#  into jax/element/mml/jax.js
#
if test -x open; then
	open -a AlphaX optable.js
fi
